import type { RuleDefinition } from "uilint-core";

export const requireTestCoverageRuleDefinition: RuleDefinition = {
  id: "require-test-coverage",
  name: "Require Test Coverage",
  description: "Enforce that source files have adequate test coverage",
  category: "coverage",
  icon: "test-tube",
  defaultSeverity: "warn",
  defaultEnabled: true,
  requirements: [
    {
      type: "coverage",
      description: "Requires test coverage data",
      setupHint: "Run tests with coverage: npm test -- --coverage",
    },
  ],
  defaultOptions: [
    {
      coveragePath: "coverage/coverage-final.json",
      threshold: 80,
      thresholdsByPattern: [],
      severity: {
        noCoverage: "error",
        belowThreshold: "warn",
      },
      testPatterns: [".test.ts", ".test.tsx", ".spec.ts", ".spec.tsx", "__tests__/"],
      ignorePatterns: ["**/*.d.ts", "**/index.ts"],
      mode: "all",
      baseBranch: "main",
    },
  ],
  optionSchema: {
    fields: [
      {
        key: "threshold",
        label: "Coverage threshold",
        type: "number",
        defaultValue: 80,
        description: "Minimum coverage percentage required (0-100)",
      },
      {
        key: "coveragePath",
        label: "Coverage file path",
        type: "text",
        defaultValue: "coverage/coverage-final.json",
        description: "Path to Istanbul coverage JSON file",
      },
      {
        key: "mode",
        label: "Mode",
        type: "select",
        defaultValue: "all",
        options: [
          { value: "all", label: "Check all code" },
          { value: "changed", label: "Only check changed lines" },
        ],
        description: "Whether to check all code or only git-changed lines",
      },
      {
        key: "chunkCoverage",
        label: "Enable chunk-level coverage",
        type: "boolean",
        defaultValue: true,
        description: "Report coverage for individual functions instead of file level",
      },
      {
        key: "focusNonReact",
        label: "Focus on non-React code",
        type: "boolean",
        defaultValue: false,
        description: "Apply strict thresholds to utilities/stores/hooks, relaxed to components",
      },
      {
        key: "chunkThreshold",
        label: "Chunk coverage threshold",
        type: "number",
        defaultValue: 80,
        description: "Minimum coverage for utility/hook/store chunks (0-100)",
      },
      {
        key: "relaxedThreshold",
        label: "Relaxed threshold for React code",
        type: "number",
        defaultValue: 50,
        description: "Threshold for components/handlers when focusNonReact is enabled",
      },
      {
        key: "minStatements",
        label: "Minimum statements for coverage",
        type: "number",
        defaultValue: 5,
        description: "Files with fewer statements are exempt from coverage requirements",
      },
    ],
  },
  docs: `
## Require Test Coverage

Enforces that source files have test coverage above a configurable threshold.

### How it Works

1. Reads Istanbul JSON coverage data (generated by vitest or jest)
2. Analyzes coverage at file, chunk (function/hook/component), and JSX element levels
3. Reports functions and files below the configured threshold

### Setup

1. Run tests with coverage: \`vitest run --coverage\`
2. Enable this rule in your ESLint config
3. Coverage data is automatically prepared when the UILint server starts

### Modes

- **All**: Checks all code against thresholds
- **Changed**: Only checks git-changed lines (useful for incremental coverage)
  `.trim(),
};

export const coverageRuleDefinitions: RuleDefinition[] = [
  requireTestCoverageRuleDefinition,
];
